### PR TITLE
chore: alter file/dir names to match eip/erc

### PR DESCRIPTION
**Pull request by JFrankfurt**
Would be nice to match the existing pattern from similar repositories. (I've got a tool that assumes the same proposal structure as EIP/ERC/CAIP and I selfishly want the integration to just be me dropping in a new url.)

Would also be nice to tweak the repo name to ENSIPs

https://github.com/ethereum/ERCs/tree/master/ERCS

image

### CODE REVIEW

**Comment by JFrankfurt** [comment]
heads up @lucemans

**Comment by JFrankfurt** [comment]
I want to include ENSIPs here https://twitter.com/jordanfrankfurt/status/1815409274220323022

**Comment by lucemans** [comment]
Interesting... ill work on making sure theyre in a standard format so that you should be able to parse them.
The current idea is that we will have
- app - for rendering a browser preview (cf pages etc) (potentially a standalone deploy)
- bot - for linting, styling, and rule-checking
- ensips - for the actual ensips (numbered by 1.md, etc)

**Comment by lucemans** [comment]
Update now that more development progress has occured!

ENSIPs can be found at [/ensips/1.md](https://github.com/ensdomains/ensips/blob/master/ensips/1.md).
For linking to an ENSIPs please link to `https://docs.ens.domains/ensip/1`

Submitting an ENSIP can be done via PR and under the `/ensip/x` path
CF Pages preview urls are available per PR as soon as CI checks pass!

Checkout the template here:
https://github.com/ensdomains/ensips/pull/4

**Comment by lucemans** [comment]
With regards to updating your extension I fear it will be slightly more then just dropping in a url.
By the looks of it a git submodule, an addition [here](https://github.com/JFrankfurt/proposal-lookup/blob/a0d4d05b176c38b46f1d5488202a4e7d32a7414f/scripts/buildSummaries.ts#L50), and [here](https://github.com/JFrankfurt/proposal-lookup/blob/a0d4d05b176c38b46f1d5488202a4e7d32a7414f/scripts/buildSummaries.ts#L58), but I hope it works out in the end!

Let me know if there is anything from my side I can do to accomodate! Closing this issue for now!

**Pull request closed without merging**
